### ISSUE TITLE
APIservice and CaBundle

### ISSUE THREAD

**Issue by JulienBalestra** [kubernetes/kube-aggregator#13]
I would like to know if there is an easy way to register Kubernetes APIServices with the certificate authority bundle from the configmap `extension-apiserver-authentication` in the namespace `kube-system`.

As example:
```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  caBundle: "REQUEST_HEADER_CLIENT_CA"
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
```

Today, I need to go through an intermediate template process to populate the `caBundle` field.

Could we think of a default `caBundle` when this field is `nil` ?

An example could be this [one](https://github.com/JulienBalestra/kube-csr/blob/8a0b8049f98b711aa35fcb3e8213238cad71f9f0/examples/metrics-server.yaml#L118-L126).
